# Generated by Django 4.2.11 on 2024-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("album", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                (
                    "album_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="album_images/images/media"
                    ),
                ),
                ("audio_file", models.FileField(upload_to="songs/media")),
            ],
        ),
    ]
